# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '����¼�.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(761, 495)
        MainWindow.setWindowFlags(Qt.WindowMinimizeButtonHint)
        MainWindow.setWindowFlags(Qt.WindowCloseButtonHint)
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox_event_type = QGroupBox(self.centralwidget)
        self.groupBox_event_type.setObjectName(u"groupBox_event_type")
        self.groupBox_event_type.setGeometry(QRect(20, 20, 351, 51))
        self.comboBox_event_type = QComboBox(self.groupBox_event_type)
        self.comboBox_event_type.setObjectName(u"comboBox_event_type")
        self.comboBox_event_type.setGeometry(QRect(10, 20, 151, 20))
        self.comboBox_event_name = QComboBox(self.groupBox_event_type)
        self.comboBox_event_name.setObjectName(u"comboBox_event_name")
        self.comboBox_event_name.setGeometry(QRect(190, 20, 151, 20))
        self.groupBox_event_attri = QGroupBox(self.centralwidget)
        self.groupBox_event_attri.setObjectName(u"groupBox_event_attri")
        self.groupBox_event_attri.setGeometry(QRect(20, 80, 351, 191))
        self.label = QLabel(self.groupBox_event_attri)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 54, 20))
        self.text_event_name = QLineEdit(self.groupBox_event_attri)
        self.text_event_name.setObjectName(u"text_event_name")
        self.text_event_name.setGeometry(QRect(70, 20, 271, 20))
        self.label_4 = QLabel(self.groupBox_event_attri)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 111, 121, 20))
        self.text_accuracy = QDoubleSpinBox(self.groupBox_event_attri)
        self.text_accuracy.setObjectName(u"text_accuracy")
        self.text_accuracy.setGeometry(QRect(101, 110, 51, 22))
        self.text_accuracy.setDecimals(2)
        self.text_accuracy.setMinimum(0.600000000000000)
        self.text_accuracy.setMaximum(1.000000000000000)
        self.text_accuracy.setSingleStep(0.010000000000000)
        self.groupBox_finish_path = QGroupBox(self.groupBox_event_attri)
        self.groupBox_finish_path.setObjectName(u"groupBox_finish_path")
        self.groupBox_finish_path.setGeometry(QRect(10, 50, 331, 51))
        self.btn_select_finish = QPushButton(self.groupBox_finish_path)
        self.btn_select_finish.setObjectName(u"btn_select_finish")
        self.btn_select_finish.setGeometry(QRect(260, 20, 61, 20))
        self.text_finish_path = QLineEdit(self.groupBox_finish_path)
        self.text_finish_path.setObjectName(u"text_finish_path")
        self.text_finish_path.setGeometry(QRect(10, 20, 241, 20))
        self.text_max_suc_run_time = QSpinBox(self.groupBox_event_attri)
        self.text_max_suc_run_time.setObjectName(u"text_max_suc_run_time")
        self.text_max_suc_run_time.setGeometry(QRect(300, 110, 42, 22))
        self.text_max_suc_run_time.setMinimum(1)
        self.text_max_suc_run_time.setMaximum(99999)
        self.label_9 = QLabel(self.groupBox_event_attri)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(170, 112, 121, 20))
        self.text_window_name = QLineEdit(self.groupBox_event_attri)
        self.text_window_name.setObjectName(u"text_window_name")
        self.text_window_name.setGeometry(QRect(90, 150, 251, 20))
        self.label_2 = QLabel(self.groupBox_event_attri)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 150, 81, 20))
        self.groupBox_micro_event_attri = QGroupBox(self.centralwidget)
        self.groupBox_micro_event_attri.setObjectName(u"groupBox_micro_event_attri")
        self.groupBox_micro_event_attri.setGeometry(QRect(20, 280, 351, 191))
        self.label_3 = QLabel(self.groupBox_micro_event_attri)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 21, 91, 20))
        self.text_gap1 = QDoubleSpinBox(self.groupBox_micro_event_attri)
        self.text_gap1.setObjectName(u"text_gap1")
        self.text_gap1.setGeometry(QRect(100, 20, 62, 22))
        self.text_gap1.setDecimals(1)
        self.text_gap1.setMinimum(0.400000000000000)
        self.text_gap1.setSingleStep(0.100000000000000)
        self.text_gap2 = QDoubleSpinBox(self.groupBox_micro_event_attri)
        self.text_gap2.setObjectName(u"text_gap2")
        self.text_gap2.setGeometry(QRect(180, 20, 62, 22))
        self.text_gap2.setDecimals(1)
        self.text_gap2.setMinimum(0.600000000000000)
        self.text_gap2.setSingleStep(0.100000000000000)
        self.label_11 = QLabel(self.groupBox_micro_event_attri)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(168, 24, 16, 16))
        self.label_12 = QLabel(self.groupBox_micro_event_attri)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(250, 27, 54, 12))
        self.label_13 = QLabel(self.groupBox_micro_event_attri)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 60, 91, 20))
        self.comboBox_action = QComboBox(self.groupBox_micro_event_attri)
        self.comboBox_action.setObjectName(u"comboBox_action")
        self.comboBox_action.setGeometry(QRect(100, 60, 171, 20))
        self.btn_select_action = QPushButton(self.groupBox_micro_event_attri)
        self.btn_select_action.setObjectName(u"btn_select_action")
        self.btn_select_action.setGeometry(QRect(280, 60, 61, 20))
        self.text_default_position = QLineEdit(self.groupBox_micro_event_attri)
        self.text_default_position.setObjectName(u"text_default_position")
        self.text_default_position.setGeometry(QRect(100, 150, 242, 20))
        self.label_14 = QLabel(self.groupBox_micro_event_attri)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(11, 150, 81, 20))
        self.groupBox_start_path = QGroupBox(self.groupBox_micro_event_attri)
        self.groupBox_start_path.setObjectName(u"groupBox_start_path")
        self.groupBox_start_path.setGeometry(QRect(10, 90, 331, 51))
        self.btn_select_start = QPushButton(self.groupBox_start_path)
        self.btn_select_start.setObjectName(u"btn_select_start")
        self.btn_select_start.setGeometry(QRect(260, 20, 61, 20))
        self.text_start_path = QLineEdit(self.groupBox_start_path)
        self.text_start_path.setObjectName(u"text_start_path")
        self.text_start_path.setGeometry(QRect(10, 20, 241, 20))
        self.groupBox_grand_event_attri = QGroupBox(self.centralwidget)
        self.groupBox_grand_event_attri.setObjectName(u"groupBox_grand_event_attri")
        self.groupBox_grand_event_attri.setGeometry(QRect(390, 80, 351, 391))
        self.groupBox_child = QGroupBox(self.groupBox_grand_event_attri)
        self.groupBox_child.setObjectName(u"groupBox_child")
        self.groupBox_child.setGeometry(QRect(10, 50, 331, 161))
        self.scrollArea_child = QScrollArea(self.groupBox_child)
        self.scrollArea_child.setObjectName(u"scrollArea_child")
        self.scrollArea_child.setGeometry(QRect(9, 50, 311, 101))
        self.scrollArea_child.setWidgetResizable(True)
        self.scrollAreaWidgetContents_2 = QWidget()
        self.scrollAreaWidgetContents_2.setObjectName(u"scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setGeometry(QRect(0, 0, 309, 99))
        self.scrollArea_child.setWidget(self.scrollAreaWidgetContents_2)
        self.btn_add_child = QPushButton(self.groupBox_child)
        self.btn_add_child.setObjectName(u"btn_add_child")
        self.btn_add_child.setGeometry(QRect(260, 20, 61, 20))
        self.comboBox_select_child = QComboBox(self.groupBox_child)
        self.comboBox_select_child.setObjectName(u"comboBox_select_child")
        self.comboBox_select_child.setGeometry(QRect(120, 20, 131, 20))
        self.comboBox_child_type = QComboBox(self.groupBox_child)
        self.comboBox_child_type.setObjectName(u"comboBox_child_type")
        self.comboBox_child_type.setGeometry(QRect(10, 20, 101, 20))
        self.text_max_rotate_time = QSpinBox(self.groupBox_grand_event_attri)
        self.text_max_rotate_time.setObjectName(u"text_max_rotate_time")
        self.text_max_rotate_time.setGeometry(QRect(232, 20, 42, 22))
        self.text_max_rotate_time.setMinimum(1)
        self.text_max_rotate_time.setMaximum(99999)
        self.label_15 = QLabel(self.groupBox_grand_event_attri)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 22, 231, 20))
        self.groupBox_exception = QGroupBox(self.groupBox_grand_event_attri)
        self.groupBox_exception.setObjectName(u"groupBox_exception")
        self.groupBox_exception.setGeometry(QRect(10, 220, 331, 161))
        self.scrollArea_exception = QScrollArea(self.groupBox_exception)
        self.scrollArea_exception.setObjectName(u"scrollArea_exception")
        self.scrollArea_exception.setGeometry(QRect(9, 50, 311, 101))
        self.scrollArea_exception.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 309, 99))
        self.scrollArea_exception.setWidget(self.scrollAreaWidgetContents_3)
        self.btn_add_exception = QPushButton(self.groupBox_exception)
        self.btn_add_exception.setObjectName(u"btn_add_exception")
        self.btn_add_exception.setGeometry(QRect(260, 20, 61, 20))
        self.comboBox_select_exception = QComboBox(self.groupBox_exception)
        self.comboBox_select_exception.setObjectName(u"comboBox_select_exception")
        self.comboBox_select_exception.setGeometry(QRect(120, 20, 131, 20))
        self.comboBox_exception_type = QComboBox(self.groupBox_exception)
        self.comboBox_exception_type.setObjectName(u"comboBox_exception_type")
        self.comboBox_exception_type.setGeometry(QRect(10, 20, 101, 20))
        self.groupBox_operation = QGroupBox(self.centralwidget)
        self.groupBox_operation.setObjectName(u"groupBox_operation")
        self.groupBox_operation.setGeometry(QRect(390, 20, 311, 51))
        self.btn_add_event = QPushButton(self.groupBox_operation)
        self.btn_add_event.setObjectName(u"btn_add_event")
        self.btn_add_event.setGeometry(QRect(20, 20, 75, 23))
        self.btn_reset = QPushButton(self.groupBox_operation)
        self.btn_reset.setObjectName(u"btn_reset")
        self.btn_reset.setGeometry(QRect(220, 20, 75, 23))
        self.btn_del_event = QPushButton(self.groupBox_operation)
        self.btn_del_event.setObjectName(u"btn_del_event")
        self.btn_del_event.setGeometry(QRect(120, 20, 75, 23))
        MainWindow.setCentralWidget(self.centralwidget)
        self.groupBox_event_attri.raise_()
        self.groupBox_event_type.raise_()
        self.groupBox_micro_event_attri.raise_()
        self.groupBox_grand_event_attri.raise_()
        self.groupBox_operation.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", "编辑事件", None))
        self.groupBox_event_type.setTitle(QCoreApplication.translate("MainWindow", u"\u4e8b\u4ef6\u9009\u62e9", None))
        self.groupBox_event_attri.setTitle(QCoreApplication.translate("MainWindow", u"\u4e8b\u4ef6\u57fa\u672c\u5c5e\u6027", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u4e8b\u4ef6\u540d\u79f0", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u8bc6\u522b\u7cbe\u786e\u5ea6", None))
        self.groupBox_finish_path.setTitle(QCoreApplication.translate("MainWindow", u"\u4e8b\u4ef6\u5b8c\u6210\u7279\u5f81\u56fe\u7247\u8def\u5f84", None))
        self.btn_select_finish.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\u4e8b\u4ef6\u6700\u5927\u8fde\u7eed\u6267\u884c\u6b21\u6570", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u7ed1\u5b9a\u7a97\u53e3\u540d\u79f0", None))
        self.groupBox_micro_event_attri.setTitle(QCoreApplication.translate("MainWindow", u"\u5fae\u4e8b\u4ef6\u5c5e\u6027", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u6267\u884c\u540e\u7b49\u5f85\u65f6\u95f4", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"(S)", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\u7ed1\u5b9a\u7684\u5177\u4f53\u52a8\u4f5c", None))
        self.btn_select_action.setText(QCoreApplication.translate("MainWindow", u"\u521b\u5efa", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\u52a8\u4f5c\u9ed8\u8ba4\u5750\u6807", None))
        self.groupBox_start_path.setTitle(QCoreApplication.translate("MainWindow", u"\u4e8b\u4ef6\u76ee\u6807\u7279\u5f81\u56fe\u7247\u8def\u5f84", None))
        self.btn_select_start.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9", None))
        self.groupBox_grand_event_attri.setTitle(QCoreApplication.translate("MainWindow", u"\u5b8f\u4e8b\u4ef6\u5c5e\u6027", None))
        self.groupBox_child.setTitle(QCoreApplication.translate("MainWindow", u"\u5b50\u4e8b\u4ef6\u5217\u8868", None))
        self.btn_add_child.setText(QCoreApplication.translate("MainWindow", u"\u6dfb\u52a0", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\u51fa\u73b0\u672a\u77e5\u5f02\u5e38\u65f6\u6700\u591a\u91cd\u590d\u5f53\u524d\u5b8f\u4e8b\u4ef6\u6b21\u6570", None))
        self.groupBox_exception.setTitle(QCoreApplication.translate("MainWindow", u"\u5f02\u5e38\u4e8b\u4ef6\u5217\u8868", None))
        self.btn_add_exception.setText(QCoreApplication.translate("MainWindow", u"\u6dfb\u52a0", None))
        self.groupBox_operation.setTitle(QCoreApplication.translate("MainWindow", u"\u64cd\u4f5c", None))
        self.btn_add_event.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
        self.btn_reset.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u7f6e", None))
        self.btn_del_event.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
    # retranslateUi

